highlight-ing/highlight-chat-frontend

src/components/App.tsx
src/hooks/useSubmitQuery.ts

Reverts highlight-ing/highlight-chat-frontend#87

Revert "feat: sending app id instead of system prompt"

---

src/components/App.tsx
src/components/Input/Input.tsx
src/types/index.ts
src/utils/attachments.ts

Handles incoming attachments better

Preprocess attachments

---

package-lock.json
package.json
src/components/App.tsx
src/components/AttachmentsButton/AttachmentsButton.tsx
src/components/Input/Input.tsx
src/hooks/useSubmitQuery.ts

Fix attachment layout

---

src/components/Messages/Message.tsx
src/hooks/useSubmitQuery.ts
src/types/index.ts

The message object is responsible for rendering

feat: show text files in original message

---

src/components/App.tsx
src/components/Messages/Message.tsx
src/hooks/useSubmitQuery.ts

Handle context fix

---

src/components/App.tsx
src/components/Input/Input.tsx
src/components/Messages/Message.tsx
src/hooks/useSubmitQuery.ts
src/types/index.ts
src/utils/attachments.ts

Passes the relevant files into the incoming message

Show multiple files of different types

---

src/hooks/useSubmitQuery.ts

Multi-file rendering

---

src/components/Attachment.tsx
src/hooks/useSubmitQuery.ts

Icons and cleanup

---

src/components/HighlightChat/HighlightChat.tsx
src/components/History/History.tsx
src/hooks/useChatHistory.ts
src/stores/messages.ts

Reverts highlight-ing/highlight-chat-frontend#137

Revert "Fix/first time loading indicator"

---

src/app/api/v1/user/prompts/route.ts
src/lib/auth.ts
src/types/supabase.ts

Adds endpoint to fetch a users owned prompts/ones they've added.

Add new /user/prompts endpoint

---

src/components/Navigation/TopTab.tsx

Hover over the tab you want to close and click the middle button on your mouse. This PR results in a 10x productivity increase 😎 (trust me bro)

feat: close tabs with middle-click

---

package-lock.json
package.json
src/components/HighlightChat/HighlightChat.tsx
src/hooks/useOnAppOpen.ts

Dependent on app runtime update:
- https://github.com/highlight-ing/highlight/pull/1332

HIG-14 start new chat when clicking tab when app is already active

---

src/utils/streamParser.ts

feat: ask for screenshot permissions

---

src/components/AttachmentsButton/AttachmentsButton.tsx

Accept markdown files as attachments

---

src/components/ChatHeader/ChatHeader.tsx

https://linear.app/highlighting/issue/HIG-83/add-back-to-home-arrow-to-this-screen

feat: add a back button to the cheat header

---

src/components/PersonalPrompts/PersonalPrompts.tsx
src/components/TrendingPrompts/TrendingPrompts.tsx
src/components/prompts/PromptEditor/screens/SettingsScreen.tsx

chore: small changes to chat home and prompts

---

.eslintrc.json
src/components/ChatHome/ChatHome.tsx
src/components/NotFoundPage/NotFoundPage.tsx
src/components/PersonalPrompts/PersonalPrompts.tsx
src/components/PersonalPrompts/customVariables.ts
src/components/ShareModal/ShareModal.tsx
src/components/TrendingPrompts/TrendingPrompts.tsx
src/components/modals/ModalContainer.tsx
src/hooks/usePromptApps.ts
src/lib/supabase.ts
src/presentations/modals/PinPromptModal.tsx
src/presentations/modals/UnpinPromptModal.tsx
src/stores/prompts.ts
src/types/index.ts
src/utils/prompts.ts

feat: pinned prompts

---

src/components/App.tsx
src/components/ChatHome/ChatHome.tsx
src/components/HighlightChat/HighlightChat.tsx
src/components/Hotkey/Hotkey.tsx
src/components/Hotkey/hotkey.module.scss
src/components/PersonalPrompts/PersonalPrompts.tsx
src/components/TrendingPrompts/TrendingPrompts.tsx
src/components/modals/BaseModal.tsx
src/components/modals/ModalContainer.tsx
src/components/modals/modals.module.scss
src/components/prompts/PromptEditor/IntelliPrompt.tsx
src/components/prompts/PromptEditor/prompteditor.module.scss
src/components/prompts/PromptListingPage/TryButton.tsx
src/hooks/useHandleConversationLoad.ts
src/hooks/useOnAppOpen.ts
src/hooks/useOnPromptChange.ts
src/hooks/usePromptApps.ts
src/hooks/useSubmitQuery.ts
src/presentations/modals/PromptAddedModal.tsx
src/presentations/modals/UnpinPromptModal.tsx
src/presentations/modals/modals.module.scss
src/types/index.ts
src/types/supabase.ts
src/utils/prompts.ts

new prompt added modal

---

src/hooks/useSubmitQuery.ts

Reverts highlight-ing/highlight-chat-frontend#227

Revert "feat: remove empty prompt"

---

src/app/api/v1/user/prompts/route.ts
src/presentations/modals/PinPromptModal.tsx
src/utils/prompts.ts

Fixes the order of the prompts returned by HL chat API.

Fix the order of prompts returned by API

---

src/app/(app)/actions.ts
src/app/api/v1/layout.tsx
src/app/prompts/[slug]/page.tsx
src/components/PromptAppIcon/PromptAppIcon.tsx
src/components/ScreenshotAttachmentPicker/ScrenshotAttachmentPicker.tsx
src/components/prompts/PromptEditor/PromptSaveButton.tsx
src/components/prompts/PromptEditor/Toolbar/VariablesTool.tsx
src/components/prompts/PromptListingPage/PromptListingPage.tsx
src/components/prompts/PromptListingPage/PromptShareButton.tsx
src/components/prompts/PromptListingPage/RelatedApp.tsx
src/components/prompts/PromptListingPage/TryButton.tsx
src/hooks/useAuth.ts
src/hooks/usePromptApps.ts
src/hooks/usePromptEditor.ts
src/lib/auth.ts
src/presentations/modals/EditPromptModal.tsx
src/stores/auth.ts
src/stores/index.ts
src/types/supabase.ts
src/utils/prompts.ts

- Adds username to prompts
- Cleanup some unused stuff

Add username + some cleanups

---

src/components/App.tsx
src/components/AttachmentsButton/AttachmentsButton.tsx
src/hooks/useSubmitQuery.ts
src/utils/contextprocessor.ts

Support all kinds of coding files. Use default attempt of parsing as text if uncertain.

Support 20+ more file types

---

package-lock.json
package.json
src/utils/attachmentUtils.ts
src/utils/formDataUtils.ts

merge this after  https://github.com/highlight-ing/highlight/tree/feature/hig-382-add-an-option-to-resend-chat-if-attachment-context-is

feat: switched to get native windows

---

src/components/Messages/Message.tsx
src/components/integrations/linear.tsx
src/components/integrations/notion.tsx

- fixes bug with copy links
- adds created with to notion + linear

Add created with

---

src/components/Messages/AssistantMessageButton.tsx
src/components/Messages/Message.tsx
src/components/integrations/linear.tsx
src/hooks/useIntegration.tsx
src/hooks/useIntegrations.tsx
src/hooks/useOnExternalMessage.ts
src/types/index.ts

Add smaller integration buttons

---

package-lock.json
package.json
src/components/HighlightChat/HighlightChat.tsx
src/components/intercom-chat.tsx

Added the intercom component. Just needs the app id for highlight and it's good to go. Styles are tweaked in the intercom dashboard.

Add intercom component

---

src/hooks/useSubmitQuery.ts
src/stores/conversation.ts

This reverts commit f635fde3adf8e892260e28d882db477b1c0f02c4, reversing changes made to 3abc13a45259aa7efa9a9f32c06cb9a9bfdd994a.

Revert "Merge pull request #393 from highlight-ing/fix/validate-uuid"

---

src/components/Input/Input.tsx
src/components/Input/chatinput.module.scss

to add some clarity of the options users have within the chat input itself
this could easily tie into nature of task and be updated to make it more relevant to the user based on previous prompt and response
https://github.com/user-attachments/assets/75f11642-23f9-4b7e-bfbe-a2071de6a445

feat: suggest simple prompts based in chat input box

---

src/utils/chatBackendUrl.ts

Reverts highlight-ing/highlight-chat-frontend#556

Revert "chore: update backend url"

---

src/hooks/usePromptEditor.ts

Edit save function to properly unpin

---

.env.sample
package.json
src/hooks/useApi.ts
src/hooks/useSubmitQuery.ts
src/presentations/modals/SendFeedbackModal.tsx
src/presentations/modals/UpdateFeedbackModal.tsx
src/utils/api-client.ts
src/utils/chatBackendUrl.ts
src/utils/formDataUtils.ts

This reverts commit c8b0cd5f788944cf85c618e23030686c81cd49f7, reversing changes made to 53d2a0e818ccbdede720e0fc983112d8834d16e2.

Revert "Merge pull request #558 from highlight-ing/feat/alpha-parsing"
